name: tekartik_common_utils
version: 0.13.5
description: Common pure dart utilities (not io or browser dependant)
homepage: https://github.com/tekartik/common_utils.dart
publish_to: none

environment:
  sdk: '>=2.13.0-0 <3.0.0'
dependencies:
  path: '>=1.8.0'
  logging: '>=1.0.0'
  pub_semver: '>=1.4.1'
  synchronized: '>=2.0.0'
  meta: '>=1.3.0'
  lints: '>=1.0.1'
  cv: '>=0.1.0 <2.0.0'
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'

dev_dependencies:
  pedantic: '>=1.10.0'
  dev_test: '>=0.15.0'
  test: '>=1.16.3'
  yaml:
  build_runner: '>=1.11.5'
  build_test: '>=1.3.7'
  build_web_compilers: '>=2.16.4'
  process_run: '>=0.12.0'

dependency_overrides:
  # cv:
  #  path: ../../../github.com/tekartik/cv.dart/packages/cv